CREATE PROCEDURE RML_SP_NOMBREARCHIVO
(
	IN DocKey INTEGER
)
AS
RUC NVARCHAR(20);
BEGIN
	SELECT "TaxIdNum" INTO RUC FROM OADM;	
	SELECT "DocNum"||'_'||:RUC||'_'||TO_VARCHAR("CreateDate",'YYYYMMDD') AS "Data"
	FROM "@BPP_PAYDTR" WHERE "DocEntry" = :DocKey;
	
END;