CREATE FUNCTION STR_FECHA_PRIMER_DIA_DEL_MES_SIGUIENTE
(
@FechaInicio date
)
RETURNS NVARCHAR(10)
BEGIN
DECLARE @FechaFinal DATE
DECLARE @Fecha NVARCHAR(10)
SELECT @FechaFinal = (SELECT CONVERT(VARCHAR(25),DATEADD(dd,-(DAY(DATEADD(mm,1,@FechaInicio))-1),DATEADD(mm,1,@FechaInicio)),101))
SET @Fecha = @FechaFinal--REPLACE(CONVERT(NVARCHAR(10),@FechaFinal),'-','')
RETURN @Fecha
END
